#"psychometric" 
  
# Summary: File containing all used packages

default_packages <- c("ggfortify",
                      "tidyverse", 
                      "expss", 
                      "xtable", 
                      "data.table", 
                      "base", 
                      "parallel", 
                      "boot", 
                      "pacman", 
                      "matrixStats", 
                      "ggplot2", 
                      "fastDummies", 
                      "gridExtra", 
                      "udpipe", 
                      "stargazer",
                      "ISwR",
                      "sjlabelled", 
                      "ggpubr", 
                      "gmodels", 
                      "pander",
                      "Cairo",
                      "pracma",
                      "fBasics",
                      "gt", 
                      "webshot",
                      "webshot2",
                      "ggtext",
                      "varhandle",
                      "viridis",
                      "plyr",
                      "readxl",
                   #   "COEF", #for tls
                      # "rgeolocate", # Deprecated as of 10/02/2023
                      "lubridate",
                      "wesanderson",
                      "fixest",
                      "XML",
                      "janitor",
                      "ivreg",
                   'openxlsx',
                   # 'rJava',
                   'plotly',
                   "grid",
                   "deming",
                   "qpdf",
                   "ggrepel",
                   "kit",
                   "gmm",
                   "lutz",
                   "sf",
                   "lavaan",
                   "DescTools",
                   "profvis",
                 "corrr",
                 'lfe',
                 "foreach",
                 "pbapply",
                 "stringi",
                 "broom",
                 "stats",
                 "haven",
                 "extrafont",
                 "hash",
                 "Hmisc",
                 "pagedown"
                      ) 